name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python for deployment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ghp-import
      
      - name: Build and deploy to GitHub Pages
        run: |
          ghp-import -n -p -f .  # This will push to the gh-pages branch automatically
          
      - name: Commit and push the updated pages
        run: |
          git config --global user.email "farhatrkhalil@gmail.com"
          git config --global user.name "farhatrkhalil"
          git commit -am "Deploy updated HTML pages"
          git push origin main
